USE PREVIDENT
/*==============================================================================================*/
                                 --PROCEDIMIENTOS ALMACENADOS--
/*==============================================================================================*/

---------- ******************************** USUARIO *****************************--------------	
	
	/*CREANDO PROCEDURE VALIDACION DE ACCESO*/

CREATE PROCEDURE USPVALIDALOGIN
  @USUARIO VARCHAR(7),
  @CONTRASENA VARCHAR(4),
  @TIPO_USUARIO VARCHAR(50),
  @MENSAJE VARCHAR(50) OUTPUT,
  @INDICE INT OUTPUT
AS
  IF((SELECT COUNT(*) FROM USUARIO WHERE USUARIO=@USUARIO)=1)
    BEGIN

	  IF((SELECT COUNT(*) FROM USUARIO WHERE USUARIO=@USUARIO AND CONTRASENA=@CONTRASENA AND TIPO_USUARIO=@TIPO_USUARIO)=1 )
	    BEGIN
		
		  IF((SELECT COUNT(*) FROM USUARIO WHERE USUARIO=@USUARIO AND CONTRASENA=@CONTRASENA AND TIPO_USUARIO=@TIPO_USUARIO AND ESTADO=1)=1)
		    BEGIN
			  SET @MENSAJE='BIENVENIDO AL SISTEMA.'
			  SET @INDICE=1
			  SELECT * FROM USUARIO WHERE USUARIO=@USUARIO AND CONTRASENA=@CONTRASENA AND TIPO_USUARIO=@TIPO_USUARIO AND ESTADO=1
			END
		  ELSE
		    BEGIN
			  SET @MENSAJE='LA CUENTA DE USUARIO ESTA BLOQUEADA.'
			  SET @INDICE=2
			END
		END
	  ELSE
	    BEGIN
		  SET @MENSAJE='LA CONTRASEÑA NO CORRESPONDE.'
		  SET @INDICE=3
		END
	END
			
  ELSE 
	BEGIN
	  SET @MENSAJE='EL USUARIO NO EXISTE.'
	  SET @INDICE=4
	END
	PRINT @MENSAJE
	PRINT @INDICE
GO
/*PROCEDIMIENTO ALMACENADO PARA REGISTRAR LOS INTENTOS DEL USUARIO*/
CREATE PROCEDURE SP_INTENTO 
@USUARIO VARCHAR(5),
@INTENTO INT,
@ESTADO INT
AS
	UPDATE USUARIO SET 
			INTENTO=@INTENTO,
			ESTADO=@ESTADO
		WHERE USUARIO=@USUARIO
GO

/*REGISTRO DE USUARIO*/
CREATE PROC SP_INSMOD_USUARIO
@COD_USUARIO CHAR(7),
@APELLIDOS VARCHAR(50),
@NOMBRE VARCHAR(50),
@USUARIO VARCHAR(5),
@CONTRASENA VARCHAR(4),
@TIPO_USUARIO VARCHAR(50),
@SEXO CHAR(1),
@ACCION INT OUTPUT
AS
	IF(@ACCION=1)
		BEGIN
			IF((SELECT COUNT(*)FROM USUARIO)=0)
				SET @COD_USUARIO='USU-001'
			ELSE
				BEGIN
					SELECT @COD_USUARIO='USU-'+ RIGHT('000' + CAST( CAST(COUNT(@COD_USUARIO)AS INT)+1 AS VARCHAR),3) FROM USUARIO
				END
			INSERT INTO USUARIO(COD_USUARIO,APELLIDOS,NOMBRE,USUARIO,CONTRASENA,SEXO,TIPO_USUARIO) VALUES(@COD_USUARIO,@APELLIDOS,@NOMBRE,@USUARIO,@CONTRASENA,@SEXO,@TIPO_USUARIO)			
			END
		ELSE
			BEGIN
				UPDATE USUARIO SET
				APELLIDOS=@APELLIDOS,
				NOMBRE=@NOMBRE,				
				USUARIO=@USUARIO,
				CONTRASENA=@CONTRASENA,
				TIPO_USUARIO=@TIPO_USUARIO,
				SEXO=@SEXO
			WHERE COD_USUARIO=@COD_USUARIO			
		END		
GO

/*LISTAR USUARIOS*/
CREATE PROC SP_LISTA_USUARIO
AS
	SELECT COD_USUARIO AS CODIGO, APELLIDOS, NOMBRE, USUARIO, 
				  CONTRASENA AS CONTRASEÑA,TIPO_USUARIO, SEXO,INTENTO, ESTADO,FECHA_REG	FROM  USUARIO 	
GO

EXEC SP_LISTA_USUARIO
GO

---------- ******************************** PACIENTES *****************************--------------

-- PROCEDIMIENTO ALMACENADO PARA  REGISTRAR PACIENTES
CREATE PROC SP_REGISTRAR_PACIENTE
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@DNI                  CHAR(8),
@GENERO               VARCHAR(30),  
@ESTADO_CIVIL         VARCHAR(30), 
@DIRECCION            VARCHAR(300), 
@DISTRITO_ID          VARCHAR(7),  
@FECHA_NACIMIENTO     DATE,     
@OBSERVACIONES        VARCHAR(500), 
@ULTIMO_ID            INT OUTPUT
AS
BEGIN

INSERT INTO PACIENTES
                         (APELLIDOS, NOMBRE, DNI, GENERO, ESTADO_CIVIL, DIRECCION, DISTRITO_ID, FECHA_NACIMIENTO, OBSERVACIONES)
VALUES        (@APELLIDOS,@NOMBRE,@DNI,@GENERO,@ESTADO_CIVIL,@DIRECCION,@DISTRITO_ID,@FECHA_NACIMIENTO,@OBSERVACIONES)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID
END
GO

-- PROCEDIMIENTO ALMACENADO PARA LISTAR PACIENTES
CREATE PROC SP_LISTAR_PACIENTES
AS
BEGIN
SELECT   PACIENTE_ID, APELLIDOS, NOMBRE, DNI, GENERO, NOMBRE_DISTRITO
FROM     PACIENTES P
INNER JOIN
DISTRITOS D ON P.DISTRITO_ID = D.DISTRITO_ID
  END
GO

EXEC SP_LISTAR_PACIENTES
GO

-- PROCEDIMIENTO ALMACENADO PARA  ACTUALIZAR PACIENTES
CREATE PROC SP_ACTUALIZAR_PACIENTE
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@DNI                  CHAR(8),
@GENERO               VARCHAR(30),  
@ESTADO_CIVIL         VARCHAR(30), 
@DIRECCION            VARCHAR(300), 
@DISTRITO_ID          VARCHAR(7),  
@FECHA_NACIMIENTO     DATE,     
@OBSERVACIONES        VARCHAR(500), 
@PACIENTE_ID            INT
AS
BEGIN
UPDATE       PACIENTES
SET  APELLIDOS = @APELLIDOS,
NOMBRE = @NOMBRE, DNI = @DNI, GENERO = @GENERO, 
ESTADO_CIVIL = @ESTADO_CIVIL, DIRECCION = @DIRECCION, 
DISTRITO_ID = @DISTRITO_ID, FECHA_NACIMIENTO = @FECHA_NACIMIENTO, 
OBSERVACIONES = @OBSERVACIONES

WHERE PACIENTE_ID   = @PACIENTE_ID  
END
GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR PACIENTES POR ID
CREATE PROC SP_BUSCAR_PACIENTES_POR_ID
@ID INT
AS
BEGIN
SELECT        PACIENTE_ID, APELLIDOS, NOMBRE, DNI, GENERO, ESTADO_CIVIL, DIRECCION, 
              FECHA_NACIMIENTO, OBSERVACIONES, P.DISTRITO_ID, PV.PROVINCIA_ID, DP.DEPARTAMENTO_ID
FROM            PACIENTES P
INNER JOIN DISTRITOS D ON P.DISTRITO_ID = D.DISTRITO_ID 
INNER JOIN PROVINCIAS PV ON D.PROVINCIA_ID = PV.PROVINCIA_ID 
INNER JOIN DEPARTAMENTOS DP ON PV.DEPARTAMENTO_ID = DP.DEPARTAMENTO_ID
WHERE PACIENTE_ID = @ID
END
GO

EXEC SP_BUSCAR_PACIENTES_POR_ID 1 
GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR PACIENTES POR NOMBRE
CREATE PROC SP_BUSCAR_PACIENTES_LIKE
@NOMBRE VARCHAR(60)
AS
BEGIN
SELECT     PACIENTE_ID, APELLIDOS, 
NOMBRE, DNI,
 GENERO, NOMBRE_DISTRITO
FROM PACIENTES P
INNER JOIN
DISTRITOS D ON P.DISTRITO_ID = D.DISTRITO_ID
WHERE NOMBRE LIKE '%'+@NOMBRE+'%'
END
GO

EXEC SP_BUSCAR_PACIENTES_LIKE 'F'
GO

-- PROCEDIMIENTO ALMACENADO PARA LISTAR PACIENTES POR ODONTÓLOGO
CREATE PROC SP_LISTAR_PACIENTES_POR_ODONTOLOGO
@ODONTOLOGO_ID INT
AS
BEGIN
SELECT  'N°'= P.PAGO_ID, 'H.C.'= D.PACIENTE_ID, 'Apellidos'= D.APELLIDOS, 'Nombre'= D.NOMBRE,'Detalle'=P.DETALLEPAGO, 'Fecha Pago'= p.FECHAPAGO, 'Estado'= P.ESTADOATENCION
FROM     PAGOS P 
INNER JOIN PACIENTES D ON P.PACIENTE_ID = D.PACIENTE_ID
INNER JOIN ODONTOLOGOS O ON P.ODONTOLOGO_ID = O.ODONTOLOGO_ID
WHERE P.ODONTOLOGO_ID = @ODONTOLOGO_ID
  END
GO
EXEC SP_LISTAR_PACIENTES_POR_ODONTOLOGO 1
GO

-- PROCEDIMIENTO ALMACENADO PARA ELIMINAR PACIENTE
CREATE PROC SP_ELIMINAR_PACIENTE
@ID INT
AS
BEGIN
DELETE FROM PACIENTES WHERE PACIENTE_ID = @ID
END
GO

---------- ******************************** TELEFONOS *****************************--------------


-- PROCEDIMIENTO ALMACENADO PARA REGISTRAR TELEFONOS
CREATE PROC SP_REGISTRAR_TELEFONOS
@OPERADOR VARCHAR(50),
@NUMERO VARCHAR(9),
@PACIENTE_ID INT
AS
BEGIN
INSERT INTO TELEFONOS
                      (OPERADOR, NUMERO, PACIENTE_ID)
VALUES     (@OPERADOR,@NUMERO,@PACIENTE_ID)
END

GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR TELEFONOS POR PACIENTE_ID
CREATE PROC SP_BUSCAR_TELEFONOS_POR_PACIENTE_ID
@ID INT
AS
BEGIN
SELECT * FROM TELEFONOS WHERE PACIENTE_ID = @ID
END
GO

EXEC SP_BUSCAR_TELEFONOS_POR_PACIENTE_ID 4
GO


-- PROCEDIMIENTO ALMACENADO PARA ELIMINAR TELEFONO
CREATE PROC SP_ELIMINAR_TELEFONO
@ID INT
AS
BEGIN
DELETE FROM TELEFONOS WHERE TELEFONO_ID = @ID
END
GO


---------- ******************************** ODONTOLOGOS *****************************--------------
-- PROCEDIMIENTO ALMACENADO PARA  REGISTRAR ODONTOLOGOS
CREATE PROC SP_REGISTRAR_ODONTOLOGO
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@DNI                  CHAR(8),
@GENERO               VARCHAR(30),  
@DIRECCION            VARCHAR(300), 
@DISTRITO_ID          VARCHAR(7),  
@FECHA_NACIMIENTO     DATE,  
@CELULAR			  VARCHAR(9),
@ULTIMO_ID            INT OUTPUT
AS
BEGIN

INSERT INTO ODONTOLOGOS
                         (APELLIDOS, NOMBRE, DNI, GENERO, DIRECCION, DISTRITO_ID, FECHA_NACIMIENTO, CELULAR)
VALUES        (@APELLIDOS,@NOMBRE,@DNI,@GENERO,@DIRECCION,@DISTRITO_ID,@FECHA_NACIMIENTO,@CELULAR)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID
END
GO

-- PROCEDIMIENTO ALMACENADO PARA LISTAR ODONTOLOGOS
CREATE PROC SP_LISTAR_ODONTOLOGOS
AS
BEGIN
SELECT   ODONTOLOGO_ID, APELLIDOS, NOMBRE, DNI, GENERO, NOMBRE_DISTRITO
FROM     ODONTOLOGOS O
INNER JOIN
DISTRITOS D ON O.DISTRITO_ID = D.DISTRITO_ID
  END
GO

EXEC SP_LISTAR_ODONTOLOGOS
GO

-- PROCEDIMIENTO ALMACENADO PARA  ACTUALIZAR ODONTOLOGOS
CREATE  PROC SP_ACTUALIZAR_ODONTOLOGO
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@DNI                  CHAR(8),
@GENERO               VARCHAR(30),  
@DIRECCION            VARCHAR(300), 
@DISTRITO_ID          VARCHAR(7),  
@FECHA_NACIMIENTO     DATE,
@CELULAR			  VARCHAR(9),
@ODONTOLOGO_ID            INT
AS
BEGIN
UPDATE       ODONTOLOGOS
SET  APELLIDOS = @APELLIDOS,
NOMBRE = @NOMBRE, DNI = @DNI, GENERO = @GENERO, 
DIRECCION = @DIRECCION, 
DISTRITO_ID = @DISTRITO_ID, FECHA_NACIMIENTO = @FECHA_NACIMIENTO, CELULAR	= @CELULAR	

WHERE ODONTOLOGO_ID   = @ODONTOLOGO_ID  
END
GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR ODONTOLOGOS POR ID
CREATE PROC SP_BUSCAR_ODONTOLOGOS_POR_ID
@ID INT
AS
BEGIN
SELECT        ODONTOLOGO_ID, APELLIDOS, NOMBRE, DNI, GENERO, DIRECCION, 
              FECHA_NACIMIENTO, CELULAR, O.DISTRITO_ID, PV.PROVINCIA_ID, DP.DEPARTAMENTO_ID
FROM            ODONTOLOGOS O
INNER JOIN DISTRITOS D ON O.DISTRITO_ID = D.DISTRITO_ID 
INNER JOIN PROVINCIAS PV ON D.PROVINCIA_ID = PV.PROVINCIA_ID 
INNER JOIN DEPARTAMENTOS DP ON PV.DEPARTAMENTO_ID = DP.DEPARTAMENTO_ID
WHERE ODONTOLOGO_ID = @ID
END
GO

EXEC SP_BUSCAR_ODONTOLOGOS_POR_ID 1 
GO


-- PROCEDIMIENTO ALMACENADO PARA ELIMINAR ODONTOLOGO
CREATE PROC SP_ELIMINAR_ODONTOLOGO
@ID INT
AS
BEGIN
DELETE FROM ODONTOLOGOS WHERE ODONTOLOGO_ID = @ID
END
GO


---------- ******************************** CONSULTAS *****************************--------------
--REGISTRAR CONSULTA
--------------------------------------------------------------------------------------------------------------------
CREATE PROC SP_REGISTRAR_CONSULTA
@FECHACONSULTA DATE,
@MOTIVO VARCHAR(100),  
@CONSULTA VARCHAR(100),  
@RECETA VARCHAR(100),  
@DIAGNOSTICO VARCHAR(100),  
@PACIENTE_ID INT, 
@ODONTOLOGO_ID INT,  
@ULTIMO_ID INT OUTPUT
AS
BEGIN

INSERT INTO CONSULTAS (FECHACONSULTA, MOTIVO, CONSULTA,RECETA,DIAGNOSTICO, PACIENTE_ID, ODONTOLOGO_ID)
VALUES            (@FECHACONSULTA, @MOTIVO, @CONSULTA,@RECETA,@DIAGNOSTICO, @PACIENTE_ID, @ODONTOLOGO_ID)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID
END
GO

-- PROCEDIMIENTO ALMACENADO PARA LISTAR CONSULTAS POR PACIENTE
CREATE PROC SP_LISTAR_CONSULTAS_POR_PACIENTE
@APELLIDOS VARCHAR(100)
AS
BEGIN
SELECT  'FECHACONSULTA'= C.FECHACONSULTA, 'MOTIVO'= C.MOTIVO,  'ATENDIDO POR'= O.APELLIDOS,'CONSULTA'= C.CONSULTA, 'RECETA'= C.RECETA, 'DIAGNOSTICO'= C.DIAGNOSTICO, 'APELLIDOS'= D.APELLIDOS,'NOMBRE'= D.NOMBRE, O.NOMBRE
FROM     CONSULTAS C 
INNER JOIN PACIENTES D ON C.PACIENTE_ID = D.PACIENTE_ID
INNER JOIN ODONTOLOGOS O ON C.ODONTOLOGO_ID = O.ODONTOLOGO_ID
WHERE D.APELLIDOS = @APELLIDOS
  END
GO
EXEC SP_LISTAR_CONSULTAS_POR_PACIENTE 'DFSDF'
GO
SELECT * FROM PACIENTES
SELECT * FROM CONSULTAS

-- PROCEDIMIENTO ALMACENADO PARA LISTAR CONSULTAS
-----------------------------------------------------------
CREATE PROC SP_LISTAR_CONSULTAS
AS
BEGIN
SELECT  'FECHACONSULTA'= C.FECHACONSULTA, 'MOTIVO'= C.MOTIVO,  'ATENDIDO POR'= O.APELLIDOS,'CONSULTA'= C.CONSULTA, 'RECETA'= C.RECETA, 'DIAGNOSTICO'= C.DIAGNOSTICO, 'APELLIDOS'= D.APELLIDOS,'NOMBRE'= D.NOMBRE, O.NOMBRE
FROM     CONSULTAS C 
INNER JOIN PACIENTES D ON C.PACIENTE_ID = D.PACIENTE_ID
INNER JOIN ODONTOLOGOS O ON C.ODONTOLOGO_ID = O.ODONTOLOGO_ID
  END
GO
EXEC SP_LISTAR_CONSULTAS
GO

---------- ******************************** PAGOS *****************************--------------
--REGISTRAR PAGO
CREATE PROC SP_REGISTRAR_PAGO
@FECHAPAGO DATE,
@MONTO MONEY,
@DETALLEPAGO VARCHAR(100),  
@PACIENTE_ID INT, 
@ODONTOLOGO_ID INT,  
@ULTIMO_ID INT OUTPUT
AS
BEGIN

INSERT INTO PAGOS (FECHAPAGO, MONTO, DETALLEPAGO , PACIENTE_ID, ODONTOLOGO_ID)
VALUES            (@FECHAPAGO, @MONTO, @DETALLEPAGO , @PACIENTE_ID, @ODONTOLOGO_ID)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID
END
GO

-- ACTUALIZAR PAGO

CREATE PROC SP_ACTUALIZAR_PAGO
@FECHAPAGO DATE,
@MONTO MONEY,
@DETALLEPAGO VARCHAR(100),  
@PACIENTE_ID INT, 
@ODONTOLOGO_ID INT,
@PAGO_ID   INT
AS
BEGIN
UPDATE    PAGOS SET  FECHAPAGO = @FECHAPAGO, MONTO = @MONTO, DETALLEPAGO = @DETALLEPAGO, PACIENTE_ID = @PACIENTE_ID ,  ODONTOLOGO_ID = @ODONTOLOGO_ID
WHERE  PAGO_ID = @PAGO_ID
END
GO
--ELIMINAR PAGO

CREATE PROC SP_ELIMINAR_PAGO
@ID INT
AS
BEGIN
DELETE FROM PAGOS WHERE PAGO_ID = @ID
END
GO
--PROCEDIMIENTO ALMACENADO PARA LISTAR PAGOS

CREATE PROC SP_LISTAR_PAGOS
AS
BEGIN
SELECT   PAGO_ID, FECHAPAGO, D.APELLIDOS + ' ' + NOMBRE, DETALLEPAGO, MONTO, P.ESTADO
FROM     PAGOS P 
INNER JOIN
PACIENTES D ON P.PACIENTE_ID = D.PACIENTE_ID order by FECHAPAGO DESC 
  END
GO
EXEC SP_LISTAR_PAGOS 

--PROCEDIMIENTO PARA BUSCAR PAGOS POR ESTADO
-----------------------------------------------------------------------
CREATE PROC SP_BUSCAR_PAGOS_LIKE
@ESTADO CHAR(9)
AS
BEGIN
SELECT   PAGO_ID, FECHAPAGO, D.APELLIDOS + ' ' + NOMBRE, DETALLEPAGO, MONTO, P.ESTADO
FROM     PAGOS P 
INNER JOIN
PACIENTES D ON P.PACIENTE_ID = D.PACIENTE_ID 
WHERE P.ESTADO LIKE '%'+@ESTADO+'%'
END
GO

EXEC SP_BUSCAR_PAGOS_LIKE 'P'


---------- ******************************** HISTORIA CLINICA *****************************--------------
-- PROCEDIMIENTO ALMACENADO PARA REGISTRAR HISTORIA CLINICA
CREATE PROC SP_REGISTRAR_HCLINICA
@ANTECEDENTE_PERSONAL VARCHAR(50),
@PACIENTE_ID INT
AS
BEGIN
INSERT INTO HISTORIALCLINICA
                      (ANTECEDENTE_PERSONAL, PACIENTE_ID)
VALUES     (@ANTECEDENTE_PERSONAL,@PACIENTE_ID)
END

GO



-- PROCEDIMIENTO ALMACENADO PARA HISTORIA CLINICA POR PACIENTE_ID
CREATE PROC SP_BUSCAR_HCLINICA_POR_PACIENTE_ID
@ID INT
AS
BEGIN
SELECT * FROM HISTORIALCLINICA WHERE PACIENTE_ID = @ID
END
GO

EXEC SP_BUSCAR_TELEFONOS_POR_PACIENTE_ID 4
GO


-- SP ACTUALIZAR HISTORIA CLINICA
CREATE PROC SP_ACTUALIZAR_HISTORIACLINICA
@ANTECEDENTE_PERSONAL VARCHAR (100),
@PACIENTE_ID INT,
@NUMERO_HISTORIA   INT
AS
BEGIN
UPDATE    HISTORIALCLINICA SET  ANTECEDENTE_PERSONAL = @ANTECEDENTE_PERSONAL, PACIENTE_ID = PACIENTE_ID
WHERE  NUMERO_HISTORIA=@NUMERO_HISTORIA

END
GO
SELECT*FROM HISTORIALCLINICA
--EXEC  SP_ACTUALIZAR_HISTORIACLINICA 'NINGUN ANTECEDENTE',3,3


-- PROCEDIMIENTO ALMACENADO PARA ELIMINAR HISTORIA CLINICA
CREATE PROC SP_ELIMINAR_HCLINICA
@ID INT
AS
BEGIN
DELETE FROM HISTORIALCLINICA WHERE NUMERO_HISTORIA = @ID
END
GO




/*==============================================================================================*/
           ---- PROCEDIMIENTO ALMACENADO PARA  REGISTRAR TURNOS--
/*==============================================================================================*/
CREATE PROC SP_REGISTRAR_TURNO
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@TURNOO                VARCHAR(30),
@FECHA				  DATE,
@HORA_ENTRADA          VARCHAR(30),
@HORA_SALIDA			  VARCHAR(30),
@ULTIMO_ID            INT OUTPUT
AS
BEGIN

INSERT INTO TURNOS
                         (APELLIDOS, NOMBRE, TURNOO, FECHA, HORA_ENTRADA, HORA_SALIDA)
VALUES        (@APELLIDOS,@NOMBRE,@TURNOO, @FECHA, @HORA_ENTRADA, @HORA_SALIDA)

SET @ULTIMO_ID = SCOPE_IDENTITY()

RETURN @ULTIMO_ID
END
GO

-- PROCEDIMIENTO ALMACENADO PARA LISTAR TURNOS
CREATE PROC SP_LISTAR_TURNOS
AS
BEGIN
SELECT  TURNO_ID, APELLIDOS, NOMBRE, TURNOO, FECHA, HORA_ENTRADA, HORA_SALIDA
FROM     TURNOS 
END
GO

EXEC SP_LISTAR_TURNOS
GO

-- PROCEDIMIENTO ALMACENADO PARA  ACTUALIZAR TURNOS
CREATE  PROC SP_ACTUALIZAR_TURNO
@APELLIDOS            VARCHAR(100),
@NOMBRE               VARCHAR(60),
@TURNOO                VARCHAR(30),
@FECHA				    DATE,
@HORA_ENTRADA          VARCHAR(30),
@HORA_SALIDA			  VARCHAR(30),
@TURNO_ID               INT
AS
BEGIN
UPDATE       TURNOS
SET  APELLIDOS = @APELLIDOS, NOMBRE = @NOMBRE, TURNOO = @TURNOO, 
	 FECHA = @FECHA, HORA_ENTRADA = @HORA_ENTRADA, HORA_SALIDA	= @HORA_SALIDA

WHERE TURNO_ID   = @TURNO_ID  
END
GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR TURNOS POR APELLIDOS
CREATE PROC SP_BUSCAR_TURNOS_LIKE
@APELLIDOS VARCHAR(100)
AS
BEGIN
SELECT     TURNO_ID, APELLIDOS, NOMBRE, TURNOO, FECHA, HORA_ENTRADA, HORA_SALIDA

FROM TURNOS
WHERE APELLIDOS LIKE '%'+@APELLIDOS+'%'
END
GO

EXEC SP_BUSCAR_TURNOS_LIKE 'F'
GO

-- PROCEDIMIENTO ALMACENADO PARA BUSCAR TURNOS POR ID
CREATE PROC SP_BUSCAR_TURNOS_POR_ID
@ID INT
AS
BEGIN
SELECT       TURNO_ID, APELLIDOS, NOMBRE, TURNOO, FECHA, HORA_ENTRADA, HORA_SALIDA

FROM            TURNOS
WHERE TURNO_ID = @ID
END
GO

EXEC SP_BUSCAR_TURNOS_POR_ID 1 
GO


-- PROCEDIMIENTO ALMACENADO PARA ELIMINAR TURNOS
CREATE PROC SP_ELIMINAR_TURNO
@ID INT
AS
BEGIN
DELETE FROM TURNOS WHERE TURNO_ID = @ID
END
GO

---------- ******************************** DEPARTAMENTOS *****************************--------------	

--PROCEDIMIENTO ALMACENADO PARA  LISTAR DEPARTAMENTOS
CREATE PROCEDURE SP_LISTAR_DEPARTAMENTOS
AS
BEGIN
	SELECT * FROM DEPARTAMENTOS
END
GO

EXEC SP_LISTAR_DEPARTAMENTOS --PERMITE VER TODOS LOS DATOS
GO

---------- ******************************** PROVINCIAS *****************************--------------	

-- PROCEDIMIENTO ALMACENADO PARA LISTAR TODAS LAS PROVINCIAS DE UN DEPARTAMENTO
CREATE PROC SP_LISTAR_PRONVINCIAS
@DEPARTAMENTO_ID VARCHAR(7)
AS
BEGIN
	SELECT * FROM PROVINCIAS WHERE DEPARTAMENTO_ID = @DEPARTAMENTO_ID
END
GO 

---------- ******************************** DISTRITOS *****************************--------------	

-- PROCEDIMIENTO ALMACENADO PARA  LISTAR TODAS LOS DISTRITOS POR PROVINCIA
CREATE PROC SP_LISTAR_DISTRITOS
@PROVINCIA_ID VARCHAR(7)
AS
BEGIN
	SELECT * FROM DISTRITOS WHERE PROVINCIA_ID = @PROVINCIA_ID
END
GO


---------- ******************************** REPORTES *****************--------------
--REPORTE DE PACIENTES
CREATE PROC SP_REPORT_PACIENTES
AS
SELECT   PACIENTE_ID, APELLIDOS, NOMBRE, DNI, GENERO, D.NOMBRE_DISTRITO
FROM     PACIENTES P
INNER JOIN  DISTRITOS D ON P.DISTRITO_ID = D.DISTRITO_ID
GO

EXEC SP_REPORT_PACIENTES

--REPORTE DE CONSULTAS POR PACIENTES
CREATE PROC SP_REPORTS_CONSULTAS_POR_FECHA
@FECHACONSULTA DATE
AS
BEGIN
SELECT  'FECHACONSULTA'= C.FECHACONSULTA, 'MOTIVO'= C.MOTIVO,  'ATENDIDO POR'= O.APELLIDOS+ ' ' +O.NOMBRE,'CONSULTA'= C.CONSULTA, 'RECETA'= C.RECETA, 'DIAGNOSTICO'= C.DIAGNOSTICO, 'APELLIDOS'= D.APELLIDOS+ ' ' +D.NOMBRE
FROM     CONSULTAS C 
INNER JOIN PACIENTES D ON C.PACIENTE_ID = D.PACIENTE_ID
INNER JOIN ODONTOLOGOS O ON C.ODONTOLOGO_ID = O.ODONTOLOGO_ID
WHERE C.FECHACONSULTA = @FECHACONSULTA
  END
GO
EXEC SP_REPORTS_CONSULTAS_POR_FECHA'2020-12-12'